//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNH.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BanSuDung
    {
        public Nullable<int> idhoadon { get; set; }
        public int idban { get; set; }
    
        public virtual BanAn BanAn { get; set; }
        public virtual HoaDon HoaDon { get; set; }
    }
}
