//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNH.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.BanSuDungs = new HashSet<BanSuDung>();
            this.HoaDonchitiets = new HashSet<HoaDonchitiet>();
        }
    
        public int idhoadon { get; set; }
        public System.DateTime ngaycheckin { get; set; }
        public Nullable<System.DateTime> ngaycheckout { get; set; }
        public int idban { get; set; }
        public Nullable<int> trangthai { get; set; }
        public Nullable<int> Tongtien { get; set; }
        public Nullable<int> idnv { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BanSuDung> BanSuDungs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonchitiet> HoaDonchitiets { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
