//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNH.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonchitiet
    {
        public int idhdct { get; set; }
        public int idhoadon { get; set; }
        public int idthucan { get; set; }
        public int soluong { get; set; }
        public Nullable<int> dongia { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual Thucan Thucan { get; set; }
    }
}
