//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNH.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thucan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Thucan()
        {
            this.HoaDonchitiets = new HashSet<HoaDonchitiet>();
        }
    
        public int id { get; set; }
        public int iddanhmuc { get; set; }
        public string ten { get; set; }
        public int gia { get; set; }
    
        public virtual Danhmucthucan Danhmucthucan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonchitiet> HoaDonchitiets { get; set; }
    }
}
